version: "3.9"
services:
 api:
   build: ./api
   container_name: api
   ports:
     - "3000:3000"
  
 myblogs:
   build: ./myblogs
   container_name: myblogs
   ports:
     - "5000:5000"
   stdin_open: true
   tty: true